---
- name: Change SSH Port
  hosts: web1
  tasks:
    - name : Ping
      ping:
    - name: replace line
      lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: '^#Port 22' 
        line: 'Port 7789'
        backrefs: yes
    - name: Restart sshd
      service:
        name: sshd
        state: restarted