---
- name: App Deployment
  hosts: '{{ target_host }}'
  vars_files:
    - ../var_files/vars_install_app_packages.yaml
  vars:
    - message: 'This message is from playbook var'
  gather_facts: '{{ facts }}'
  tasks:
    - name: Ping
      ping:

    - name: Print Message
      debug:
        msg: '{{ message }}'

    - name: Print Facts
      debug:
        msg: '{{ target_host }} Operating System is: {{ ansible_distribution }}'